name: Passing Value test

on:
  workflow_dispatch:

jobs:
  # GITHUB_ENV で共有
  Between-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Set the value
        run: |
          echo "test_value=pien" >> $GITHUB_ENV

      - name: Use the value
        run: |
          # This will output 'pien'
          echo "${{ env.test_value }}"

  # outputs で共有
  Between-jobs-1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test_value }}
    steps:
      - id: step1
        run: |
          echo "test_value=hello" >> $GITHUB_OUTPUT
  Between-jobs-2:
    runs-on: ubuntu-latest
    needs: [Between-jobs-1]
    steps:
      - run: echo ${{needs.Between-jobs-1.outputs.output1}}
